<?php
// module/Etudiant/view/etudiant/etudiant/index.phtml:

$title = 'Note';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

        
<table class="table">
<tr>
    <th>Etudiant</th>
    <th>Exercice</th>
    <th>Note</th>
    <th>Action</th>
    
</tr>
<?php foreach($etudiants as $etudiant) : ?>
<tr>
    <td><?php echo $this->escapeHtml($etudiant->nom);?></td>
    <td><?php echo $this->escapeHtml($etudiant->exercice);?></td>   
    <td><?php echo $this->escapeHtml($etudiant->note);?></td>    
  <td> <a href="<?php echo $this->url('etudiant',
            array('action'=>'edit', 'id' => $etudiant->id));?>">Ajouter Note</a>
  
    </td>
</tr>
<?php endforeach; ?>
</table>
